"""Router registry for the FastAPI surface."""

from . import (
    admin,
    advisor,
    briefing,
    engagement,
    goals,
    greeting,
    insights,
    intel,
    journal,
    memory,
    onboarding,
    pageview,
    profile,
    projects,
    recommendations,
    research,
    settings,
    suggestions,
    threads,
    user,
)

ROUTERS = (
    settings.router,
    journal.router,
    advisor.router,
    goals.router,
    intel.router,
    research.router,
    onboarding.router,
    briefing.router,
    greeting.router,
    recommendations.router,
    engagement.router,
    profile.router,
    projects.router,
    user.router,
    pageview.router,
    admin.router,
    insights.router,
    suggestions.router,
    memory.router,
    threads.router,
)
